In [ ]:
import os
from pathlib import Path
import sys

BASE_DIR = Path.cwd().parent
sys.path.append(str(BASE_DIR))

PROCESSED_DIR = BASE_DIR / "data"/ "processed"

processed_paths_dict = { 
    "beta": os.path.join()
    "mean_volatility": os.path.join(PROCESSED_DIR, "mean_volatility.parquet"),
    "microstructure": os.path.join(PROCESSED_DIR, "microstructure.parquet"),
    "momentum": os.path.join(PROCESSED_DIR, "momentum.parquet"),
    "momentum_liquidity": os.path.join(PROCESSED_DIR, "momentum_liquidity.parquet"),
    "pvo": os.path.join(PROCESSED_DIR, "pvo.parquet"), 
    "reversal_illiquidity": os.path.join(PROCESSED_DIR, "reversal_illiquidity.parquet")
}

In [2]:
BASE_DIR

WindowsPath('c:/Users/Gordon Li/Desktop/systematic_project')

In [3]:
import numpy as np 
import pandas as pd

from scripts.research.ic import IC
from scripts.research.targets import ForwardReturns

In [4]:
returns_df = ForwardReturns([5, 10, 21]).run_data()

factors_df_dict = {}
for key, path in processed_paths_dict.items(): 
    factors_df_dict[key] = pd.read_parquet(path)

In [5]:
IC(returns_df, factors_df_dict["mean_volatility"]).run_data()

,mean_volatility_5,mean_volatility_10,mean_volatility_21,mean_volatility_63
mean_ic,0.009669,0.017355,0.025301,0.017202
std_ic,0.113740,0.117239,0.115819,0.108339
ic_ir,0.085012,0.148033,0.218455,0.158784
positive_ic_rate,0.527000,0.542714,0.585366,0.553079
n_periods,1000.000000,995.000000,984.000000,942.000000

In [7]:
IC(returns_df, factors_df_dict["microstructure"]).run_data()

,dv_liquidity_21,dv_liquidity_63,dv_liquidity_126,amihud_21,amihud_63,amihud_126
mean_ic,-0.005130,-0.004696,-0.004703,-0.015177,-0.013601,-0.011618
std_ic,0.098103,0.098018,0.098077,0.117492,0.117501,0.116596
ic_ir,-0.052292,-0.047914,-0.047956,-0.129177,-0.115751,-0.099643
positive_ic_rate,0.479920,0.474872,0.474019,0.446231,0.442505,0.450106
n_periods,996.000000,975.000000,943.000000,995.000000,974.000000,942.000000

In [8]:
IC(returns_df, factors_df_dict["momentum_liquidity"]).run_data()

,momentum_liquidity_21,momentum_liquidity_63,momentum_liquidity_126
mean_ic,0.017059,0.015945,0.015756
std_ic,0.137701,0.134880,0.132579
ic_ir,0.123882,0.118216,0.118843
positive_ic_rate,0.565574,0.556011,0.565574
n_periods,732.000000,732.000000,732.000000

In [6]:
IC(returns_df, factors_df_dict["pvo"]).run_data()

                  pvo_((0.01, 0.99), (26, 12))
ic_ir                                 0.053927
mean_ic                               0.005249
n_periods                          1004.000000
positive_ic_rate                      0.504980
std_ic                                0.097328

In [ ]:
momentum_liquidity