In [6]:
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\Gordon Li\Desktop\systematic_project")
sys.path.insert(0, str(ROOT))

# verify it's actually first
print("sys.path[0] =", sys.path[0])

sys.path[0] = C:\Users\Gordon Li\Desktop\systematic_project

In [1]:
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\Gordon Li\Desktop\systematic_project")
sys.path.insert(0, str(ROOT))

# optional sanity checks
print("sys.path[0]:", sys.path[0])

sys.path[0]: C:\Users\Gordon Li\Desktop\systematic_project

In [7]:
from scripts.signals import Kalman

ModuleNotFoundError: No module named 'scripts.signals'

In [8]:
from scripts.signals import Kalman

kalman_pipeline = Kalman()
kalman_pipeline.plot_kalman_comparison(["CBA.AX", "ZIP.AX"])

ModuleNotFoundError: No module named 'scripts.signals'

In [2]:
import yfinance as yf
import pandas as pd

In [3]:
ticker = yf.Ticker("ZIP.AX")

# 1) Daily adjusted close over 4 years
prices = ticker.history(period="4y", auto_adjust=True)[["Close"]].copy()
prices.index = pd.to_datetime(prices.index).tz_localize(None)

# 2) Quarterly balance sheet (preferred for smoother P/B series)
# If quarterly is empty, fall back to annual balance sheet
bs = ticker.quarterly_balance_sheet.copy()
bs

                                                      2025-06-30
Ordinary Shares Number                              1.292156e+09
Share Issued                                        1.292156e+09
Net Debt                                            2.019008e+09
Total Debt                                          2.423997e+09
Tangible Book Value                                 4.418830e+08
Invested Capital                                    3.120149e+09
Working Capital                                     1.331980e+08
Net Tangible Assets                                 4.418830e+08
Capital Lease Obligations                           1.336800e+07
Common Stock Equity                                 7.095200e+08
Total Capitalization                                3.120149e+09
Total Equity Gross Minority Interest                7.095200e+08
Stockholders Equity                                 7.095200e+08
Gains Losses Not Affecting Retained Earnings        1.346420e+08
Other Equity Adjustments                            6.943500e+07
Foreign Currency Translation Adjustments            6.520700e+07
Retained Earnings                                  -2.180485e+09
Capital Stock                                       2.755363e+09
Other Capital Stock                                 1.638480e+08
Common Stock                                        2.591515e+09
Total Liabilities Net Minority Interest             2.795148e+09
Total Non Current Liabilities Net Minority Inte...  2.423997e+09
Long Term Debt And Capital Lease Obligation         2.423997e+09
Long Term Capital Lease Obligation                  1.336800e+07
Long Term Debt                                      2.410629e+09
Current Liabilities                                 3.711510e+08
Pensionand Other Post Retirement Benefit Plans ...  2.454000e+07
Payables And Accrued Expenses                       3.466110e+08
Payables                                            3.466110e+08
Other Payable                                       2.948980e+08
Accounts Payable                                    5.171300e+07
Total Assets                                        3.504668e+09
Total Non Current Assets                            3.000319e+09
Non Current Deferred Assets                         6.019400e+07
Non Current Deferred Taxes Assets                   6.019400e+07
Non Current Accounts Receivable                     2.657141e+09
Goodwill And Other Intangible Assets                2.676370e+08
Other Intangible Assets                             5.534300e+07
Goodwill                                            2.122940e+08
Net PPE                                             1.534700e+07
Gross PPE                                           1.534700e+07
Other Properties                                    1.271200e+07
Machinery Furniture Equipment                       2.635000e+06
Current Assets                                      5.043490e+08
Prepaid Assets                                      1.031600e+07
Receivables                                         9.780000e+07
Other Receivables                                   9.780000e+07
Cash Cash Equivalents And Short Term Investments    3.962330e+08
Other Short Term Investments                        4.612000e+06
Cash And Cash Equivalents                           3.916210e+08
Cash Financial                                      3.916210e+08

In [4]:
bs_q = ticker.quarterly_balance_sheet.copy()
bs_a = ticker.balance_sheet.copy()

bs = bs_q if not bs_q.empty and bs_q.shape[1] >= 4 else bs_a

In [5]:
bs

,2025-06-30,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Ordinary Shares Number,1.292156e+09,1.126660e+09,8.246470e+08,6.879360e+08,NaN
Share Issued,1.292156e+09,1.126660e+09,8.246470e+08,6.879360e+08,NaN
Net Debt,2.019008e+09,2.050134e+09,2.642466e+09,2.462130e+09,NaN
Total Debt,2.423997e+09,2.420234e+09,2.936093e+09,2.765864e+09,NaN
Tangible Book Value,4.418830e+08,9.297000e+07,-1.165330e+08,2.164000e+07,NaN
Invested Capital,3.120149e+09,2.801673e+09,3.152716e+09,3.198559e+09,NaN
Working Capital,1.331980e+08,1.813370e+08,1.478210e+08,2.200320e+08,NaN
Net Tangible Assets,4.418830e+08,9.297000e+07,-1.165330e+08,2.164000e+07,NaN
Capital Lease Obligations,1.336800e+07,1.709400e+07,1.771700e+07,4.039000e+06,NaN
Common Stock Equity,7.095200e+08,3.985330e+08,2.343400e+08,4.367340e+08,NaN
Total Capitalization,3.120149e+09,2.801673e+09,3.152716e+09,3.198559e+09,NaN
Total Equity Gross Minority Interest,7.095200e+08,3.985330e+08,2.343400e+08,4.377490e+08,NaN
Minority Interest,NaN,NaN,NaN,1.015000e+06,NaN
Stockholders Equity,7.095200e+08,3.985330e+08,2.343400e+08,4.367340e+08,NaN
Gains Losses Not Affecting Retained Earnings,1.346420e+08,1.552960e+08,1.585510e+08,1.523850e+08,NaN
Other Equity Adjustments,6.943500e+07,7.623500e+07,7.538400e+07,8.213000e+07,NaN
Foreign Currency Translation Adjustments,6.520700e+07,7.906100e+07,8.316700e+07,7.025500e+07,NaN
Retained Earnings,-2.180485e+09,-2.260380e+09,-2.160218e+09,-1.871613e+09,NaN
Capital Stock,2.755363e+09,2.503617e+09,2.236007e+09,2.155962e+09,NaN
Other Capital Stock,1.638480e+08,1.638480e+08,1.144660e+08,1.144660e+08,NaN
Common Stock,2.591515e+09,2.339769e+09,2.121541e+09,2.041496e+09,NaN
Total Liabilities Net Minority Interest,2.795148e+09,2.783727e+09,3.160427e+09,2.948410e+09,NaN
Total Non Current Liabilities Net Minority Interest,2.423997e+09,2.506723e+09,2.937982e+09,2.792048e+09,NaN
Other Non Current Liabilities,NaN,8.648900e+07,1.889000e+06,2.618400e+07,6990000.0
Non Current Deferred Liabilities,NaN,NaN,NaN,NaN,10312000.0
Non Current Deferred Taxes Liabilities,NaN,NaN,NaN,NaN,10312000.0
Long Term Debt And Capital Lease Obligation,2.423997e+09,2.420234e+09,2.936093e+09,2.765864e+09,NaN
Long Term Capital Lease Obligation,1.336800e+07,1.709400e+07,1.771700e+07,4.039000e+06,NaN
Long Term Debt,2.410629e+09,2.403140e+09,2.918376e+09,2.761825e+09,NaN
Current Liabilities,3.711510e+08,2.770040e+08,2.224450e+08,1.563620e+08,NaN
Pensionand Other Post Retirement Benefit Plans Current,2.454000e+07,1.853900e+07,8.808000e+06,9.068000e+06,NaN
Payables And Accrued Expenses,3.466110e+08,2.584650e+08,2.136370e+08,1.472940e+08,NaN
Payables,3.466110e+08,2.584650e+08,2.136370e+08,1.472940e+08,NaN
Other Payable,2.948980e+08,2.131460e+08,1.499270e+08,1.096880e+08,NaN
Accounts Payable,5.171300e+07,4.531900e+07,6.371000e+07,3.760600e+07,NaN
Total Assets,3.504668e+09,3.182260e+09,3.394767e+09,3.386159e+09,NaN
Total Non Current Assets,3.000319e+09,2.723919e+09,3.024501e+09,3.009765e+09,NaN
Other Non Current Assets,NaN,NaN,1.384600e+07,NaN,NaN
Non Current Deferred Assets,6.019400e+07,NaN,3.696900e+07,NaN,10312000.0
Non Current Deferred Taxes Assets,6.019400e+07,NaN,3.696900e+07,NaN,10312000.0
Non Current Accounts Receivable,2.657141e+09,2.398592e+09,2.596832e+09,2.514871e+09,NaN
Investments And Advances,NaN,NaN,2.248000e+06,7.074100e+07,26040000.0
Other Investments,NaN,NaN,NaN,NaN,19034000.0
Long Term Equity Investment,NaN,NaN,2.248000e+06,7.074100e+07,7006000.0
Investmentsin Associatesat Cost,NaN,NaN,2.248000e+06,7.074100e+07,7006000.0
Goodwill And Other Intangible Assets,2.676370e+08,3.055630e+08,3.508730e+08,4.150940e+08,NaN
Other Intangible Assets,5.534300e+07,9.608700e+07,1.416380e+08,1.923500e+08,NaN
Goodwill,2.122940e+08,2.094760e+08,2.092350e+08,2.227440e+08,NaN
Net PPE,1.534700e+07,1.976400e+07,2.373300e+07,9.059000e+06,NaN
Gross PPE,1.534700e+07,1.976400e+07,2.373300e+07,9.059000e+06,NaN
Other Properties,1.271200e+07,1.690700e+07,1.864100e+07,3.813000e+06,NaN
Machinery Furniture Equipment,2.635000e+06,2.857000e+06,5.092000e+06,5.246000e+06,NaN
Current Assets,5.043490e+08,4.583410e+08,3.702660e+08,3.763940e+08,NaN
Prepaid Assets,1.031600e+07,9.712000e+06,1.009800e+07,1.100500e+07,NaN
Receivables,9.780000e+07,9.111300e+07,7.706200e+07,6.183000e+07,NaN
Other Receivables,9.780000e+07,9.111300e+07,7.706200e+07,6.183000e+07,NaN
Cash Cash Equivalents And Short Term Investments,3.962330e+08,3.575160e+08,2.831060e+08,3.035590e+08,NaN
Other Short Term Investments,4.612000e+06,4.510000e+06,7.196000e+06,3.864000e+06,NaN
Cash And Cash Equivalents,3.916210e+08,3.530060e+08,2.759100e+08,2.996950e+08,NaN
Cash Financial,3.916210e+08,3.530060e+08,2.759100e+08,2.996950e+08,NaN