In [6]:
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\Gordon Li\Desktop\systematic_project")
sys.path.insert(0, str(ROOT))

# verify it's actually first
print("sys.path[0] =", sys.path[0])

sys.path[0] = C:\Users\Gordon Li\Desktop\systematic_project

In [5]:
import datetime as dt

end_date = dt.datetime.today().date()

end_date_year = end_date.year
end_date_month = end_date.strftime("%B")

end_date_month

'June'

In [20]:
from google import genai
from dotenv import load_dotenv

from pydantic import BaseModel, Field

from google.genai import types

In [17]:
class ReleaseEntry(BaseModel): 
    reference_month: dt.date = Field(description="The first day of the reference month, e.g., '2026-04-01'")
    release_date: dt.date = Field(description="The date of the release, e.g., '2026-04-15'")

class ABSReleaseCalendar(BaseModel):
    releases: list[ReleaseEntry] = Field(description="Chronological list of all release dates")

In [21]:
load_dotenv()

client = genai.Client()

prompt_information = f"""
                Generate a clean historical release schedule for the Australia Bureau of Statistics (ABS) 
                Labour Force unemployment rate from January 2022 to April 2026. Keep the entries in 
                chronological order.
            """

In [ ]:
response = client.models.generate_content(
            model="gemini-3.1-flash-lite",
            
            
            contents = prompt_information, 
            config = types.GenerateContentConfig(
                response_mime_type = "application/json", 
                response_schema = ABSReleaseCalendar, 
                temperature = 0.05
            )
        )
print(response.text)

{
  "releases": [
    {
      "reference_month": "2022-01-01",
      "release_date": "2022-02-17"
    },
    {
      "reference_month": "2022-02-01",
      "release_date": "2022-03-17"
    },
    {
      "reference_month": "2022-03-01",
      "release_date": "2022-04-14"
    },
    {
      "reference_month": "2022-04-01",
      "release_date": "2022-05-19"
    },
    {
      "reference_month": "2022-05-01",
      "release_date": "2022-06-16"
    },
    {
      "reference_month": "2022-06-01",
      "release_date": "2022-07-14"
    },
    {
      "reference_month": "2022-07-01",
      "release_date": "2022-08-18"
    },
    {
      "reference_month": "2022-08-01",
      "release_date": "2022-09-15"
    },
    {
      "reference_month": "2022-09-01",
      "release_date": "2022-10-20"
    },
    {
      "reference_month": "2022-10-01",
      "release_date": "2022-11-17"
    },
    {
      "reference_month": "2022-11-01",
      "release_date": "2022-12-15"
    },
    {
      "reference_month": "2022-12-01",
      "release_date": "2023-01-19"
    },
    {
      "reference_month": "2023-01-01",
      "release_date": "2023-02-23"
    },
    {
      "reference_month": "2023-02-01",
      "release_date": "2023-03-16"
    },
    {
      "reference_month": "2023-03-01",
      "release_date": "2023-04-13"
    },
    {
      "reference_month": "2023-04-01",
      "release_date": "2023-05-18"
    },
    {
      "reference_month": "2023-05-01",
      "release_date": "2023-06-15"
    },
    {
      "reference_month": "2023-06-01",
      "release_date": "2023-07-13"
    },
    {
      "reference_month": "2023-07-01",
      "release_date": "2023-08-17"
    },
    {
      "reference_month": "2023-08-01",
      "release_date": "2023-09-14"
    },
    {
      "reference_month": "2023-09-01",
      "release_date": "2023-10-19"
    },
    {
      "reference_month": "2023-10-01",
      "release_date": "2023-11-16"
    },
    {
      "reference_month": "2023-11-01",
      "release_date": "2023-12-14"
    },
    {
      "reference_month": "2023-12-01",
      "release_date": "2024-01-18"
    },
    {
      "reference_month": "2024-01-01",
      "release_date": "2024-02-15"
    },
    {
      "reference_month": "2024-02-01",
      "release_date": "2024-03-14"
    },
    {
      "reference_month": "2024-03-01",
      "release_date": "2024-04-18"
    },
    {
      "reference_month": "2024-04-01",
      "release_date": "2024-05-16"
    },
    {
      "reference_month": "2024-05-01",
      "release_date": "2024-06-13"
    },
    {
      "reference_month": "2024-06-01",
      "release_date": "2024-07-18"
    },
    {
      "reference_month": "2024-07-01",
      "release_date": "2024-08-15"
    },
    {
      "reference_month": "2024-08-01",
      "release_date": "2024-09-19"
    },
    {
      "reference_month": "2024-09-01",
      "release_date": "2024-10-17"
    },
    {
      "reference_month": "2024-10-01",
      "release_date": "2024-11-14"
    },
    {
      "reference_month": "2024-11-01",
      "release_date": "2024-12-12"
    },
    {
      "reference_month": "2024-12-01",
      "release_date": "2025-01-23"
    },
    {
      "reference_month": "2025-01-01",
      "release_date": "2025-02-20"
    },
    {
      "reference_month": "2025-02-01",
      "release_date": "2025-03-20"
    },
    {
      "reference_month": "2025-03-01",
      "release_date": "2025-04-17"
    },
    {
      "reference_month": "2025-04-01",
      "release_date": "2025-05-15"
    },
    {
      "reference_month": "2025-05-01",
      "release_date": "2025-06-19"
    },
    {
      "reference_month": "2025-06-01",
      "release_date": "2025-07-17"
    },
    {
      "reference_month": "2025-07-01",
      "release_date": "2025-08-14"
    },
    {
      "reference_month": "2025-08-01",
      "release_date": "2025-09-18"
    },
    {
      "reference_month": "2025-09-01",
      "release_date": "2025-10-16"
    },
    {
      "reference_month": "2025-10-01",
      "release_date": "2025-11-13"
    },
    {
      "reference_month": "2025-11-01",
      "release_date": "2025-12-11"
    },
    {
      "reference_month": "2025-12-01",
      "release_date": "2026-01-22"
    },
    {
      "reference_month": "2026-01-01",
      "release_date": "2026-02-19"
    },
    {
      "reference_month": "2026-02-01",
      "release_date": "2026-03-19"
    },
    {
      "reference_month": "2026-03-01",
      "release_date": "2026-04-16"
    },
    {
      "reference_month": "2026-04-01",
      "release_date": "2026-05-14"
    }
  ]
}

In [8]:
from scripts.signals import Kalman

kalman_pipeline = Kalman()
kalman_pipeline.plot_kalman_comparison(["CBA.AX", "ZIP.AX"])

ModuleNotFoundError: No module named 'scripts.signals'

In [2]:
import yfinance as yf
import pandas as pd

In [31]:
start_date = pd.to_datetime("2026-02-12")
end_date = pd.to_datetime("2026-02-25")

In [1]:
import datetime
from dbnomics import fetch_series

# Calculate the date for 4 years ago from today
four_years_ago = (datetime.date.today() - datetime.timedelta(days=4*365)).strftime('%Y-%m-%d')

# Fetch the exact Australian 2-Year Bond dataset tracked by the RBA
df = fetch_series('RBA/F2/FCMYGBAG2D')

In [2]:
df

,@frequency,provider_code,dataset_code,dataset_name,series_code,series_name,original_period,period,original_value,value,FREQ,units,Frequency,Units
0,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2013-05-20,2013-05-20,NA,NaN,D,per-cent-per-annum,Daily,Per cent per annum
1,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2013-05-21,2013-05-21,NA,NaN,D,per-cent-per-annum,Daily,Per cent per annum
2,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2013-05-22,2013-05-22,NA,NaN,D,per-cent-per-annum,Daily,Per cent per annum
3,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2013-05-23,2013-05-23,NA,NaN,D,per-cent-per-annum,Daily,Per cent per annum
4,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2013-05-24,2013-05-24,NA,NaN,D,per-cent-per-annum,Daily,Per cent per annum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3292,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2026-05-21,2026-05-21,4.618,4.618,D,per-cent-per-annum,Daily,Per cent per annum
3293,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2026-05-22,2026-05-22,4.578,4.578,D,per-cent-per-annum,Daily,Per cent per annum
3294,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2026-05-25,2026-05-25,4.564,4.564,D,per-cent-per-annum,Daily,Per cent per annum
3295,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2026-05-26,2026-05-26,4.591,4.591,D,per-cent-per-annum,Daily,Per cent per annum
3296,daily,RBA,F2,Capital market yields – government bonds,FCMYGBAG2D,Australian Government 2 year bond,2026-05-27,2026-05-27,4.542,4.542,D,per-cent-per-annum,Daily,Per cent per annum

In [17]:
string = """
Hi Frederico, just applied for the Data Analyst role at Mirvac. I've got 1st Class Hons in Stats (UNSW) plus SQL, Python and Power BI experience. Built this dashboard tracking data quality/validation, thought it might be relevant: https://shorturl.at/2TCOk

Look forward to hearing from you!
Gordon
"""
print(len(string))

300

In [11]:
print(len("https://trusted-data-appuct-dashboard-bdzs4fha6magtwovadrbgm.streamlit.app/"))

75

In [ ]:
data = yf.download("CBA.AX", start=start_date, end=end_date, auto

        Date  Dividends
0 2022-02-16       1.75
1 2022-08-17       2.10
2 2023-02-22       2.10
3 2023-08-16       2.40
4 2024-02-21       2.15
5 2024-08-21       2.50
6 2025-02-19       2.25
7 2025-08-20       2.60
8 2026-02-18       2.35

In [27]:
import readabs as ra

import pandas as pd

data, meta = ra.read_abs_cat("6202.0")

IndexError: list index out of range

In [25]:
import pandas as pd

In [29]:
exchange_2022_url = r"https://www.rba.gov.au/statistics/tables/xls-hist/2018-2022.xls"
exchange_2022 = pd.read_excel(exchange_2022_url, sheet_name="Data", header=0)
exchange_2022.head(10)

,F11.1 EXCHANGE RATES,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Title,A$1=USD,Trade-weighted Index May 1970 = 100,A$1=CNY,A$1=JPY,A$1=EUR,A$1=KRW,A$1=GBP,A$1=SGD,A$1=INR,...,A$1=IDR,A$1=VND,A$1=AED,A$1=PGK,A$1=HKD,A$1=CAD,A$1=ZAR,A$1=CHF,A$1=PHP,A$1=SDR
1,Description,AUD/USD Exchange Rate; see notes for further d...,Australian Dollar Trade-weighted Index,AUD/CNY Exchange Rate,AUD/JPY Exchange Rate,AUD/EUR Exchange Rate,AUD/KRW Exchange Rate,AUD/GBP Exchange Rate,AUD/SGD Exchange Rate,AUD/INR Exchange Rate,...,AUD/IDR Exchange Rate,AUD/VND Exchange Rate,AUD/AED Exchange Rate,AUD/PGK Exchange Rate,AUD/HKD Exchange Rate,AUD/CAD Exchange Rate,AUD/ZAR Exchange Rate,AUD/CHF Exchange Rate,AUD/PHP Exchange Rate,AUD/SDR Exchange Rate
2,Frequency,Daily,Daily,Daily,Daily,Daily,Daily,Daily,Daily,Daily,...,Daily,Daily,Daily,Daily,Daily,Daily,Daily,Daily,Daily,Daily
3,Type,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative,...,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative,Indicative
4,Units,USD,Index,CNY,JPY,EUR,KRW,GBP,SGD,INR,...,IDR,VND,AED,PGK,HKD,CAD,ZAR,CHF,PHP,SDR
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Source,WM/Reuters,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,...,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,IMF
8,Publication date,2023-03-15 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00,...,2023-03-15 00:00:00,2023-03-15 00:00:00,2020-12-01 00:00:00,2022-07-06 00:00:00,2023-03-15 00:00:00,2022-12-28 00:00:00,2014-11-28 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00,2023-03-15 00:00:00
9,Series ID,FXRUSD,FXRTWI,FXRCR,FXRJY,FXREUR,FXRSKW,FXRUKPS,FXRSD,FXRIRE,...,FXRIR,FXRVD,FXRUAED,FXRPNGK,FXRHKD,FXRCD,FXRSARD,FXRSF,FXRPHP,FXRSDR

In [ ]:
feature_rename_dict = dict()
for col_feature, col_name in zip(series_type, unemployment.columns):
    ficture_rename_dict[col_name] = "unemployment_" + 
print(unemployment.columns)

In [8]:
data, meta = ra.read_abs_cat("6202.0")

IndexError: list index out of range

In [ ]:
div_events = (
    dividends.set_index("Date")["Dividends"].sort_index()
)

calendar = pd.date_range(
    start=min(div_events.index.min(), ptd_df["Date"].min()),
    end=ptd_df["Date"].max(),
    freq="D"
)

Date
1992-04-03    0.200195
1992-10-01    0.200195
1993-04-02    0.200195
1993-09-29    0.220215
1994-03-31    0.240234
                ...
2024-02-21    2.150000
2024-08-21    2.500000
2025-02-19    2.250000
2025-08-20    2.600000
2026-02-18    2.350000
Name: Dividends, Length: 69, dtype: float64

In [4]:
bs_q = ticker.quarterly_balance_sheet.copy()
bs_a = ticker.balance_sheet.copy()

bs = bs_q if not bs_q.empty and bs_q.shape[1] >= 4 else bs_a

In [5]:
bs

,2026-03-31,2025-09-30,2025-03-31,2024-09-30
Treasury Shares Number,3.168494e+06,NaN,3.994601e+06,5.352012e+06
Ordinary Shares Number,3.011030e+09,2.983752e+09,2.967371e+09,2.974064e+09
Share Issued,3.014199e+09,2.983752e+09,2.971366e+09,2.979416e+09
Net Debt,3.011600e+10,9.600000e+10,2.885100e+10,9.098400e+10
Total Debt,2.126180e+11,2.198240e+11,2.315110e+11,2.050870e+11
Tangible Book Value,6.546900e+10,6.536300e+10,6.570200e+10,6.434600e+10
Invested Capital,2.836710e+11,2.898460e+11,3.030780e+11,2.738320e+11
Net Tangible Assets,6.546900e+10,6.536300e+10,6.570200e+10,6.434600e+10
Common Stock Equity,7.105300e+10,7.112800e+10,7.156700e+10,6.985700e+10
Total Capitalization,2.836710e+11,2.898460e+11,3.030780e+11,2.738320e+11
Total Equity Gross Minority Interest,7.175600e+10,7.186700e+10,7.233100e+10,7.062800e+10
Minority Interest,7.030000e+08,7.390000e+08,7.640000e+08,7.710000e+08
Stockholders Equity,7.105300e+10,7.112800e+10,7.156700e+10,6.985700e+10
Retained Earnings,4.574500e+10,4.449200e+10,4.469700e+10,4.344900e+10
Capital Stock,2.913800e+10,2.819100e+10,2.786000e+10,2.818200e+10
Common Stock,2.913800e+10,2.819100e+10,2.786000e+10,2.818200e+10
Total Liabilities Net Minority Interest,1.242049e+12,1.225241e+12,1.230278e+12,1.158487e+12
Derivative Product Liabilities,5.946600e+10,4.390200e+10,4.427900e+10,5.525400e+10
Long Term Debt And Capital Lease Obligation,2.126180e+11,2.198240e+11,2.315110e+11,2.050870e+11
Payables,3.230000e+08,8.849000e+09,3.940000e+08,9.633000e+09
Other Payable,NaN,8.312000e+09,NaN,9.273000e+09
Total Tax Payable,3.230000e+08,5.370000e+08,3.940000e+08,3.600000e+08
Total Assets,1.313805e+12,1.297108e+12,1.302609e+12,1.229115e+12
Investments And Advances,2.848590e+11,2.625630e+11,2.521700e+11,2.421180e+11
Investmentin Financial Assets,2.837150e+11,2.614210e+11,2.506740e+11,2.406740e+11
Available For Sale Securities,1.639360e+11,1.649990e+11,1.551990e+11,1.403860e+11
Financial Assets Designatedas Fair Value Through Profitor Loss Total,6.430000e+08,6.940000e+08,1.780000e+08,1.630000e+08
Trading Securities,5.122500e+10,4.824800e+10,4.574500e+10,4.575500e+10
Long Term Equity Investment,1.144000e+09,1.142000e+09,1.496000e+09,1.444000e+09
Investmentsin Associatesat Cost,1.144000e+09,1.142000e+09,1.496000e+09,1.444000e+09
Goodwill And Other Intangible Assets,5.584000e+09,5.765000e+09,5.865000e+09,5.511000e+09
Other Intangible Assets,NaN,1.600000e+09,NaN,1.090000e+09
Goodwill,NaN,4.165000e+09,NaN,4.421000e+09
Net PPE,1.989000e+09,2.144000e+09,2.172000e+09,2.222000e+09
Receivables,3.532000e+09,3.739000e+09,4.072000e+09,4.401000e+09
Taxes Receivable,9.500000e+07,3.300000e+07,2.560000e+08,4.600000e+07
Cash And Cash Equivalents,1.825020e+11,1.227180e+11,2.026600e+11,1.129910e+11
Cash Financial,1.655390e+11,1.205000e+09,1.957910e+11,1.198000e+09
Cash Cash Equivalents And Federal Funds Sold,1.825020e+11,1.791460e+11,2.026600e+11,1.571160e+11