In [6]:
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\Gordon Li\Desktop\systematic_project")
sys.path.insert(0, str(ROOT))

# verify it's actually first
print("sys.path[0] =", sys.path[0])

sys.path[0] = C:\Users\Gordon Li\Desktop\systematic_project

In [1]:
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\Gordon Li\Desktop\systematic_project")
sys.path.insert(0, str(ROOT))

# optional sanity checks
print("sys.path[0]:", sys.path[0])

sys.path[0]: C:\Users\Gordon Li\Desktop\systematic_project

In [7]:
from scripts.signals import Kalman

ModuleNotFoundError: No module named 'scripts.signals'

In [8]:
from scripts.signals import Kalman

kalman_pipeline = Kalman()
kalman_pipeline.plot_kalman_comparison(["CBA.AX", "ZIP.AX"])

ModuleNotFoundError: No module named 'scripts.signals'

In [2]:
import yfinance as yf
import pandas as pd

In [31]:
start_date = pd.to_datetime("2026-02-12")
end_date = pd.to_datetime("2026-02-25")

In [3]:
ticker = yf.Ticker("GGP.AX")

income_stmt = ticker.balance_sheet.copy()
income_stmt

,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Treasury Shares Number,NaN,0.0,NaN,NaN
Ordinary Shares Number,670618774.0,670618774.0,4.070547e+09,3.947270e+09
Share Issued,670618774.0,670618774.0,4.070547e+09,3.947270e+09
Net Debt,36685000.0,10354000.0,3.271700e+07,5.977733e+06
Total Debt,41802000.0,41915000.0,4.338100e+07,1.253819e+07
Tangible Book Value,0.0,0.0,5.726000e+06,4.154893e+06
Invested Capital,0.0,0.0,4.882900e+07,1.634468e+07
Working Capital,0.0,0.0,1.483200e+07,7.134881e+06
Net Tangible Assets,0.0,0.0,5.726000e+06,4.154893e+06
Capital Lease Obligations,309000.0,412000.0,2.780000e+05,3.483990e+05
Common Stock Equity,0.0,0.0,5.726000e+06,4.154893e+06
Total Capitalization,0.0,0.0,4.882900e+07,1.634468e+07
Total Equity Gross Minority Interest,0.0,0.0,5.726000e+06,4.154893e+06
Stockholders Equity,0.0,0.0,5.726000e+06,4.154893e+06
Other Equity Interest,13492000.0,10173000.0,3.350000e+05,1.775920e+05
Retained Earnings,-71657000.0,-56820000.0,-3.571800e+07,-2.438886e+07
Additional Paid In Capital,70998000.0,70821000.0,3.616600e+07,2.406431e+07
Capital Stock,5091000.0,5069000.0,4.071000e+06,3.947270e+06
Common Stock,5091000.0,5069000.0,4.071000e+06,3.947270e+06
Total Liabilities Net Minority Interest,0.0,0.0,4.954500e+07,1.984347e+07
Total Non Current Liabilities Net Minority Interest,0.0,0.0,4.514900e+07,1.632996e+07
Other Non Current Liabilities,3000.0,NaN,NaN,NaN
Non Current Pension And Other Postretirement Benefit Plans,98000.0,63000.0,2.900000e+04,3.334100e+04
Long Term Debt And Capital Lease Obligation,41669000.0,41787000.0,4.317300e+07,1.248324e+07
Long Term Capital Lease Obligation,176000.0,284000.0,7.000000e+04,2.934520e+05
Long Term Debt,41493000.0,41503000.0,4.310300e+07,1.218979e+07
Long Term Provisions,1912000.0,1887000.0,1.947000e+06,3.846713e+06
Current Liabilities,0.0,0.0,4.396000e+06,3.513512e+06
Current Debt And Capital Lease Obligation,133000.0,128000.0,2.080000e+05,5.494700e+04
Current Capital Lease Obligation,133000.0,128000.0,2.080000e+05,5.494700e+04
Pensionand Other Post Retirement Benefit Plans Current,0.0,186000.0,9.190000e+05,1.026070e+05
Current Provisions,NaN,186000.0,9.190000e+05,NaN
Payables,795000.0,1712000.0,1.331000e+06,2.091368e+06
Other Payable,NaN,28000.0,9.490000e+05,5.020160e+05
Total Tax Payable,171000.0,192000.0,2.810000e+05,4.196470e+05
Accounts Payable,624000.0,1492000.0,1.010000e+05,1.169705e+06
Total Assets,0.0,0.0,5.527100e+07,2.399836e+07
Total Non Current Assets,0.0,0.0,3.604300e+07,1.334997e+07
Investmentin Financial Assets,39000.0,88000.0,0.000000e+00,NaN
Financial Assets Designatedas Fair Value Through Profitor Loss Total,39000.0,88000.0,0.000000e+00,NaN
Net PPE,82840000.0,60697000.0,3.604300e+07,1.334997e+07
Accumulated Depreciation,-285000.0,-272000.0,-2.670000e+05,-2.640870e+05
Gross PPE,714000.0,774000.0,6.340000e+05,7.263550e+05
Other Properties,503000.0,609000.0,4.780000e+05,5.892870e+05
Machinery Furniture Equipment,179000.0,145000.0,1.560000e+05,1.309010e+05
Buildings And Improvements,32000.0,20000.0,0.000000e+00,6.167000e+03
Properties,0.0,0.0,0.000000e+00,0.000000e+00
Current Assets,0.0,0.0,1.922800e+07,1.064839e+07
Other Current Assets,630000.0,414000.0,4.270000e+05,1.542150e+05
Prepaid Assets,1510000.0,12576000.0,8.415000e+06,4.203923e+06
Other Receivables,108000.0,NaN,NaN,7.819800e+04
Taxes Receivable,29000.0,116000.0,0.000000e+00,NaN
Cash Cash Equivalents And Short Term Investments,4808000.0,31149000.0,1.038600e+07,6.212057e+06
Cash And Cash Equivalents,4808000.0,31149000.0,1.038600e+07,6.212057e+06
Cash Equivalents,105000.0,5355000.0,0.000000e+00,NaN
Cash Financial,4703000.0,25794000.0,1.038600e+07,6.212057e+06

In [ ]:
data = yf.download("CBA.AX", start=start_date, end=end_date, auto

        Date  Dividends
0 2022-02-16       1.75
1 2022-08-17       2.10
2 2023-02-22       2.10
3 2023-08-16       2.40
4 2024-02-21       2.15
5 2024-08-21       2.50
6 2025-02-19       2.25
7 2025-08-20       2.60
8 2026-02-18       2.35

In [27]:
import readabs as ra

import pandas as pd

data, meta = ra.read_abs_cat("6202.0")

IndexError: list index out of range

In [2]:
import pandas as pd

In [21]:
unemployment_url = r"https://www.abs.gov.au/statistics/labour/employment-and-unemployment/labour-force-australia/apr-2026/62020001.xlsx"
unemployment = pd.read_excel(unemployment_url, sheet_name="Data1", header=0)
unemployment = unemployment.set_index("Unnamed: 0")
unemployment.index.name = "Date"
rel_cols = unemployment.columns[unemployment.loc["Series ID"].isin(["A84423134K","A84423050A"])]
unemployment = unemployment[rel_cols]
series_type = list(unemployment.loc["Series Type", :])

series_type_mapping = { 
    "Trend": "trend", 
    "Seasonally Adjusted": "seasonal"
}


feature_rename_dict = dict()
for col_feature, col_name in zip(series_type, unemployment.columns):
    feature_rename_dict[col_name] = "unemployment_" + series_type_mapping[col_feature]
print(feature_rename_dict)

unemployment = unemployment.rename(columns=feature_rename_dict)

unemployment = unemployment.reset_index()
unemployment.head(10)

{'Unemployment rate ;  Persons ;': 'unemployment_trend', 'Unemployment rate ;  Persons ;.1': 'unemployment_seasonal'}

                  Date   unemployment_trend unemployment_seasonal
0                 Unit              Percent               Percent
1          Series Type                Trend   Seasonally Adjusted
2            Data Type              PERCENT               PERCENT
3            Frequency                Month                 Month
4     Collection Month                    1                     1
5         Series Start  1978-02-01 00:00:00   1978-02-01 00:00:00
6           Series End  2026-04-01 00:00:00   2026-04-01 00:00:00
7              No. Obs                  579                   579
8            Series ID           A84423134K            A84423050A
9  1978-02-01 00:00:00             6.303886              6.644703

In [ ]:
feature_rename_dict = dict()
for col_feature, col_name in zip(series_type, unemployment.columns):
    ficture_rename_dict[col_name] = "unemployment_" + 
print(unemployment.columns)

In [8]:
data, meta = ra.read_abs_cat("6202.0")

IndexError: list index out of range

In [ ]:
div_events = (
    dividends.set_index("Date")["Dividends"].sort_index()
)

calendar = pd.date_range(
    start=min(div_events.index.min(), ptd_df["Date"].min()),
    end=ptd_df["Date"].max(),
    freq="D"
)

Date
1992-04-03    0.200195
1992-10-01    0.200195
1993-04-02    0.200195
1993-09-29    0.220215
1994-03-31    0.240234
                ...
2024-02-21    2.150000
2024-08-21    2.500000
2025-02-19    2.250000
2025-08-20    2.600000
2026-02-18    2.350000
Name: Dividends, Length: 69, dtype: float64

In [4]:
bs_q = ticker.quarterly_balance_sheet.copy()
bs_a = ticker.balance_sheet.copy()

bs = bs_q if not bs_q.empty and bs_q.shape[1] >= 4 else bs_a

In [5]:
bs

,2026-03-31,2025-09-30,2025-03-31,2024-09-30
Treasury Shares Number,3.168494e+06,NaN,3.994601e+06,5.352012e+06
Ordinary Shares Number,3.011030e+09,2.983752e+09,2.967371e+09,2.974064e+09
Share Issued,3.014199e+09,2.983752e+09,2.971366e+09,2.979416e+09
Net Debt,3.011600e+10,9.600000e+10,2.885100e+10,9.098400e+10
Total Debt,2.126180e+11,2.198240e+11,2.315110e+11,2.050870e+11
Tangible Book Value,6.546900e+10,6.536300e+10,6.570200e+10,6.434600e+10
Invested Capital,2.836710e+11,2.898460e+11,3.030780e+11,2.738320e+11
Net Tangible Assets,6.546900e+10,6.536300e+10,6.570200e+10,6.434600e+10
Common Stock Equity,7.105300e+10,7.112800e+10,7.156700e+10,6.985700e+10
Total Capitalization,2.836710e+11,2.898460e+11,3.030780e+11,2.738320e+11
Total Equity Gross Minority Interest,7.175600e+10,7.186700e+10,7.233100e+10,7.062800e+10
Minority Interest,7.030000e+08,7.390000e+08,7.640000e+08,7.710000e+08
Stockholders Equity,7.105300e+10,7.112800e+10,7.156700e+10,6.985700e+10
Retained Earnings,4.574500e+10,4.449200e+10,4.469700e+10,4.344900e+10
Capital Stock,2.913800e+10,2.819100e+10,2.786000e+10,2.818200e+10
Common Stock,2.913800e+10,2.819100e+10,2.786000e+10,2.818200e+10
Total Liabilities Net Minority Interest,1.242049e+12,1.225241e+12,1.230278e+12,1.158487e+12
Derivative Product Liabilities,5.946600e+10,4.390200e+10,4.427900e+10,5.525400e+10
Long Term Debt And Capital Lease Obligation,2.126180e+11,2.198240e+11,2.315110e+11,2.050870e+11
Payables,3.230000e+08,8.849000e+09,3.940000e+08,9.633000e+09
Other Payable,NaN,8.312000e+09,NaN,9.273000e+09
Total Tax Payable,3.230000e+08,5.370000e+08,3.940000e+08,3.600000e+08
Total Assets,1.313805e+12,1.297108e+12,1.302609e+12,1.229115e+12
Investments And Advances,2.848590e+11,2.625630e+11,2.521700e+11,2.421180e+11
Investmentin Financial Assets,2.837150e+11,2.614210e+11,2.506740e+11,2.406740e+11
Available For Sale Securities,1.639360e+11,1.649990e+11,1.551990e+11,1.403860e+11
Financial Assets Designatedas Fair Value Through Profitor Loss Total,6.430000e+08,6.940000e+08,1.780000e+08,1.630000e+08
Trading Securities,5.122500e+10,4.824800e+10,4.574500e+10,4.575500e+10
Long Term Equity Investment,1.144000e+09,1.142000e+09,1.496000e+09,1.444000e+09
Investmentsin Associatesat Cost,1.144000e+09,1.142000e+09,1.496000e+09,1.444000e+09
Goodwill And Other Intangible Assets,5.584000e+09,5.765000e+09,5.865000e+09,5.511000e+09
Other Intangible Assets,NaN,1.600000e+09,NaN,1.090000e+09
Goodwill,NaN,4.165000e+09,NaN,4.421000e+09
Net PPE,1.989000e+09,2.144000e+09,2.172000e+09,2.222000e+09
Receivables,3.532000e+09,3.739000e+09,4.072000e+09,4.401000e+09
Taxes Receivable,9.500000e+07,3.300000e+07,2.560000e+08,4.600000e+07
Cash And Cash Equivalents,1.825020e+11,1.227180e+11,2.026600e+11,1.129910e+11
Cash Financial,1.655390e+11,1.205000e+09,1.957910e+11,1.198000e+09
Cash Cash Equivalents And Federal Funds Sold,1.825020e+11,1.791460e+11,2.026600e+11,1.571160e+11